aligned_service_manager_address: "0xf5059a5D33d5853360D16C683c16e67980206f36"
proof_aggregation_service_address: "0x162A433068F51e18b7d13932F27e66a3f99E6890"
eth_rpc_url: "http://localhost:8545"
eth_ws_url: "ws://localhost:8546"
max_proofs_in_queue: 1000
last_aggregated_block_filepath: config-files/proof-aggregator.last_aggregated_block.json

ecdsa:
  private_key_store_path: "config-files/anvil.proof-aggregator.ecdsa.key.json"
  private_key_store_password: ""
