{
 "title": "Aggregation Mode",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "User error response count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "floor(\n  increase(api_response_code{job=\"gateway-http\",statuscode=~\"4..\"}[10y])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Server Error response count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "floor(\n  increase(api_response_code{job=\"gateway-http\",statuscode=~\"5..\"}[10y])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Success response count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "floor(\n  increase(api_response_code{job=\"gateway-http\",statuscode=~\"2..\",endpoint!=\"/metrics\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gateway Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "source": "url",
       "type": "json",
       "url": "http://host.docker.internal:8089",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "DB posts latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 18 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(time_elapsed_db_query_bucket{query=\"sp1-post\"}[10y])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DB posts throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(time_elapsed_db_query_count[10y]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Poller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Payment events (placeholder)",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT * FROM payment_events LIMIT 50 "
      }
     ]
    },
    {
     "title": "Last Processed Block",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "last_processed_block{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Active Subscriptions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "active_subscriptions{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{bot=\"poller\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Proof Aggregator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true
  },
  {
   "title": "Ethereum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Block",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "json_options": {
        "root_is_not_array": true
       },
       "method": "POST",
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"\n| project \"block_number\"=\"number\"",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"eth_blockNumber\",\n  \"params\": [],\n  \"id\": 1\n}",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Current Gas Price (wei)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "json_options": {
        "root_is_not_array": true
       },
       "method": "POST",
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"eth_gasPrice\",\n  \"params\": [],\n  \"id\": 1\n}",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Payments contract",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Address",
     "type": "stat",
     "gridPos": { "h": 3, "w": 14, "x": 5, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "json_options": {
        "columnar": false,
        "root_is_not_array": true
       },
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n    \"jsonrpc\": \"2.0\",\n    \"method\": \"eth_call\",\n    \"params\": [\n      {\n        \"to\": \"0xd84c0fEfEaEf69A51836DBf607E031a9033a4ed7\",\n        \"data\": \"0x18160ddd\"\n      },\n      \"latest\"\n    ],\n    \"id\": 1\n  }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Cost in Gwei",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{ \"jsonrpc\": \"2.0\", \"method\": \"eth_call\", \"params\": [ { \"to\": \"0x922D6956C99E12DFeB3224DEA977D0939758A1Fe\", \"data\": \"0x07f56ad4\" }, \"latest\" ], \"id\": 1 }",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Expiration time in days",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{ \"jsonrpc\": \"2.0\", \"method\": \"eth_call\", \"params\": [ { \"to\": \"0x922D6956C99E12DFeB3224DEA977D0939758A1Fe\", \"data\": \"0x86925476\" }, \"latest\" ], \"id\": 1 }",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Subscription Limit",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{ \"jsonrpc\": \"2.0\", \"method\": \"eth_call\", \"params\": [ { \"to\": \"0x922D6956C99E12DFeB3224DEA977D0939758A1Fe\", \"data\": \"0xa4ece875\" }, \"latest\" ], \"id\": 1 }",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Max Subscription Time Ahead (in days)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{ \"jsonrpc\": \"2.0\", \"method\": \"eth_call\", \"params\": [ { \"to\": \"0x922D6956C99E12DFeB3224DEA977D0939758A1Fe\", \"data\": \"0x051c7de3\" }, \"latest\" ], \"id\": 1 }",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Active Subscriptions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{ \"jsonrpc\": \"2.0\", \"method\": \"eth_call\", \"params\": [ { \"to\": \"0x922D6956C99E12DFeB3224DEA977D0939758A1Fe\", \"data\": \"0x93588bee\" }, \"latest\" ], \"id\": 1 }",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Funds recipient",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{ \"jsonrpc\": \"2.0\", \"method\": \"eth_call\", \"params\": [ { \"to\": \"0x922D6956C99E12DFeB3224DEA977D0939758A1Fe\", \"data\": \"0x2c42a9dd\" }, \"latest\" ], \"id\": 1 }",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Proof Aggregator contract",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "RISC0 ID",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "json_options": {
        "columnar": false,
        "root_is_not_array": true
       },
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n    \"jsonrpc\": \"2.0\",\n    \"method\": \"eth_call\",\n    \"params\": [\n      {\n        \"to\": \"0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc\",\n        \"data\": \"0x972e58ba\"\n      },\n      \"latest\"\n    ],\n    \"id\": 1\n  }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "RISC0 Verifier",
     "type": "stat",
     "gridPos": { "h": 6, "w": 9, "x": 7, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{ \"jsonrpc\": \"2.0\", \"method\": \"eth_call\", \"params\": [ { \"to\": \"0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc\", \"data\": \"0x616af4f7\" }, \"latest\" ], \"id\": 1 }",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Address",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "json_options": {
        "columnar": false,
        "root_is_not_array": true
       },
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n    \"jsonrpc\": \"2.0\",\n    \"method\": \"eth_call\",\n    \"params\": [\n      {\n        \"to\": \"0xd84c0fEfEaEf69A51836DBf607E031a9033a4ed7\",\n        \"data\": \"0x18160ddd\"\n      },\n      \"latest\"\n    ],\n    \"id\": 1\n  }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "SP1 ID",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "json_options": {
        "columnar": false,
        "root_is_not_array": true
       },
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n    \"jsonrpc\": \"2.0\",\n    \"method\": \"eth_call\",\n    \"params\": [\n      {\n        \"to\": \"0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc\",\n        \"data\": \"0x6eecb4c9\"\n      },\n      \"latest\"\n    ],\n    \"id\": 1\n  }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "SP1 Verifier",
     "type": "stat",
     "gridPos": { "h": 6, "w": 9, "x": 7, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{ \"jsonrpc\": \"2.0\", \"method\": \"eth_call\", \"params\": [ { \"to\": \"0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc\", \"data\": \"0x294e3ccb\" }, \"latest\" ], \"id\": 1 }",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Owner",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{ \"jsonrpc\": \"2.0\", \"method\": \"eth_call\", \"params\": [ { \"to\": \"0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc\", \"data\": \"0x8da5cb5b\" }, \"latest\" ], \"id\": 1 }",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Proof Aggregator",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{ \"jsonrpc\": \"2.0\", \"method\": \"eth_call\", \"params\": [ { \"to\": \"0xcbEAF3BDe82155F56486Fb5a1072cb8baAf547cc\", \"data\": \"0x4c46688c\" }, \"latest\" ], \"id\": 1 }",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Proof Aggregator Balance in ETH",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 15, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "root_selector": "$.result",
       "source": "url",
       "type": "json",
       "uql": "parse-json\n| scope \"result\"",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"eth_getBalance\",\n  \"params\": [\n    \"0xa0ee7a142d267c1f36714e4a8f75612f20a79720\",\n    \"latest\"\n  ],\n  \"id\": 1\n}",
        "headers": [
         { "key": "Content-Type", "value": "application/json" }
        ],
        "method": "POST"
       }
      }
     ]
    }
   ]
  }
 ]
}