name: test-sp1

on:
  push:
    branches:
      - testnet
      - staging
  pull_request:
    branches: ["*"]
    paths:
      - 'operator/sp1/**'
      - '.github/workflows/test-sp1.yml'

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
          with:
            go-version: '1.22'
            cache: false
        - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
          with:
            toolchain: stable
        - name: Test SP1 Rust
          run: make test_sp1_rust_ffi
        - name: Test SP1 go bindings
          run: make test_sp1_go_bindings_linux
